[2022-08-03 15:26:34,266] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:11.179248+00:00 [queued]>
[2022-08-03 15:26:34,691] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:11.179248+00:00 [queued]>
[2022-08-03 15:26:34,717] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:26:34,726] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 15:26:34,735] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:26:34,974] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 15:26:11.179248+00:00
[2022-08-03 15:26:35,236] {standard_task_runner.py:52} INFO - Started process 480 to run task
[2022-08-03 15:26:35,266] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T15:26:11.179248+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpx0cqo49x', '--error-file', '/tmp/tmpbaow_b24']
[2022-08-03 15:26:35,297] {standard_task_runner.py:80} INFO - Job 28: Subtask create_table
[2022-08-03 15:26:35,994] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:11.179248+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 15:26:37,531] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T15:26:11.179248+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T15:26:11.179248+00:00
[2022-08-03 15:26:37,584] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 200, in run
    self.log.debug("Executing %d statements", len(sql))
TypeError: object of type 'function' has no len()
[2022-08-03 15:26:37,694] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T152611, start_date=20220803T152634, end_date=20220803T152637
[2022-08-03 15:26:37,786] {standard_task_runner.py:97} ERROR - Failed to execute job 28 for task create_table (object of type 'function' has no len(); 480)
[2022-08-03 15:26:38,058] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 15:26:38,983] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
