[2022-08-03 22:48:43,552] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T22:47:52.905561+00:00 [queued]>
[2022-08-03 22:48:43,575] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T22:47:52.905561+00:00 [queued]>
[2022-08-03 22:48:43,582] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 22:48:43,586] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 22:48:43,592] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 22:48:43,626] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 22:47:52.905561+00:00
[2022-08-03 22:48:43,645] {standard_task_runner.py:52} INFO - Started process 5820 to run task
[2022-08-03 22:48:43,655] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T22:47:52.905561+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmppls2f0s4', '--error-file', '/tmp/tmp4t3fk7tl']
[2022-08-03 22:48:43,662] {standard_task_runner.py:80} INFO - Job 260: Subtask create_table
[2022-08-03 22:48:43,945] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T22:47:52.905561+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 22:48:44,535] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T22:47:52.905561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T22:47:52.905561+00:00
[2022-08-03 22:48:46,389] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 22:48:46,833] {dbapi.py:231} INFO - Running statement: CREATE TABLE vehicles (
                    id TEXT,
                    vin TEXT,
                    price TEXT,
                    miles TEXT, 
                    stock_no TEXT, 
                    year TEXT, 
                    make TEXT, 
                    model TEXT, 
                    trim TEXT, 
                    body_type TEXT, 
                    vehicle_type TEXT, 
                    drivetrain TEXT, 
                    transmission TEXT, 
                    fuel_type TEXT, 
                    engine_size TEXT, 
                    engine_block TEXT,
                    seller_name TEXT, 
                    street TEXT, 
                    city TEXT, 
                    state TEXT, 
                    zip  TEXT
                    );      
                , parameters: None
[2022-08-03 22:48:46,890] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "vehicles" already exists

[2022-08-03 22:48:47,095] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T224752, start_date=20220803T224843, end_date=20220803T224847
[2022-08-03 22:48:47,280] {standard_task_runner.py:97} ERROR - Failed to execute job 260 for task create_table (relation "vehicles" already exists
; 5820)
[2022-08-03 22:48:47,471] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 22:48:47,728] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
