[2022-08-03 16:42:42,773] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:42:25.812156+00:00 [queued]>
[2022-08-03 16:42:42,792] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:42:25.812156+00:00 [queued]>
[2022-08-03 16:42:42,798] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:42:42,803] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 16:42:42,810] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:42:42,848] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load-data> on 2022-08-03 16:42:25.812156+00:00
[2022-08-03 16:42:42,866] {standard_task_runner.py:52} INFO - Started process 1887 to run task
[2022-08-03 16:42:42,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'load-data', 'manual__2022-08-03T16:42:25.812156+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpwo90cbfw', '--error-file', '/tmp/tmplqs3lyye']
[2022-08-03 16:42:42,891] {standard_task_runner.py:80} INFO - Job 79: Subtask load-data
[2022-08-03 16:42:43,241] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:42:25.812156+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 16:42:43,514] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=load-data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T16:42:25.812156+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T16:42:25.812156+00:00
[2022-08-03 16:42:43,535] {postgres.py:127} INFO - Running copy expert: COPY logs FROM STDIN WITH DELIMITER ',' CSV HEADER , filename: /opt/***/files/vehicle_challenge.csv
[2022-08-03 16:42:43,647] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 16:42:43,705] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 54, in insert_data
    post_hook.copy_expert("COPY logs FROM STDIN WITH DELIMITER ',' CSV HEADER ",'/opt/airflow/files/vehicle_challenge.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.UndefinedTable: relation "logs" does not exist

[2022-08-03 16:42:43,971] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=load-data, execution_date=20220803T164225, start_date=20220803T164242, end_date=20220803T164243
[2022-08-03 16:42:44,053] {standard_task_runner.py:97} ERROR - Failed to execute job 79 for task load-data (relation "logs" does not exist
; 1887)
[2022-08-03 16:42:44,123] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 16:42:44,417] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
