[2022-08-03 15:28:32,844] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T15:28:26.294919+00:00 [queued]>
[2022-08-03 15:28:32,863] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T15:28:26.294919+00:00 [queued]>
[2022-08-03 15:28:32,866] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:28:32,869] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 15:28:32,873] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:28:32,896] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): load-data> on 2022-08-03 15:28:26.294919+00:00
[2022-08-03 15:28:32,924] {standard_task_runner.py:52} INFO - Started process 557 to run task
[2022-08-03 15:28:32,933] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'load-data', 'manual__2022-08-03T15:28:26.294919+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpalnjd2ah', '--error-file', '/tmp/tmpev6cmkjx']
[2022-08-03 15:28:32,941] {standard_task_runner.py:80} INFO - Job 31: Subtask load-data
[2022-08-03 15:28:33,076] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T15:28:26.294919+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 15:28:33,511] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=load-data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T15:28:26.294919+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T15:28:26.294919+00:00
[2022-08-03 15:28:33,555] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 15:28:33,581] {dbapi.py:231} INFO - Running statement: 
            COPY vehicles (id, vin, price, miles, stock_no, year, make, model, trim, body_type, vehicle_type, drivetrain, transmission, fuel_type, engine_size, engine_block, seller_name, street, city, state, zip)
            FROM PROGRAM 'gzip -dc files/vehicle_challenge.csv.gz' DELIMITER ',' CSV HEADER;, parameters: None
[2022-08-03 15:28:33,595] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "vin" of relation "vehicles" does not exist

[2022-08-03 15:28:33,644] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=load-data, execution_date=20220803T152826, start_date=20220803T152832, end_date=20220803T152833
[2022-08-03 15:28:33,701] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task load-data (column "vin" of relation "vehicles" does not exist
; 557)
[2022-08-03 15:28:33,825] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 15:28:33,941] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
