[2022-08-03 15:26:27,783] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:09.185050+00:00 [queued]>
[2022-08-03 15:26:28,163] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:09.185050+00:00 [queued]>
[2022-08-03 15:26:28,190] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:26:28,219] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 15:26:28,230] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:26:28,585] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 15:26:09.185050+00:00
[2022-08-03 15:26:28,746] {standard_task_runner.py:52} INFO - Started process 479 to run task
[2022-08-03 15:26:28,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T15:26:09.185050+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpgbapatdy', '--error-file', '/tmp/tmp4z5xt2nh']
[2022-08-03 15:26:29,000] {standard_task_runner.py:80} INFO - Job 27: Subtask create_table
[2022-08-03 15:26:31,710] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T15:26:09.185050+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 15:26:33,546] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T15:26:09.185050+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T15:26:09.185050+00:00
[2022-08-03 15:26:33,766] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 200, in run
    self.log.debug("Executing %d statements", len(sql))
TypeError: object of type 'function' has no len()
[2022-08-03 15:26:33,939] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T152609, start_date=20220803T152627, end_date=20220803T152633
[2022-08-03 15:26:34,199] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task create_table (object of type 'function' has no len(); 479)
[2022-08-03 15:26:34,835] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 15:26:35,449] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
