[2022-08-03 16:08:48,213] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:08:38.105006+00:00 [queued]>
[2022-08-03 16:08:48,229] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:08:38.105006+00:00 [queued]>
[2022-08-03 16:08:48,231] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:08:48,236] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 16:08:48,239] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:08:48,255] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load-data> on 2022-08-03 16:08:38.105006+00:00
[2022-08-03 16:08:48,268] {standard_task_runner.py:52} INFO - Started process 537 to run task
[2022-08-03 16:08:48,274] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'load-data', 'manual__2022-08-03T16:08:38.105006+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpfgostju9', '--error-file', '/tmp/tmpgj__5k7x']
[2022-08-03 16:08:48,280] {standard_task_runner.py:80} INFO - Job 59: Subtask load-data
[2022-08-03 16:08:48,407] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:08:38.105006+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 16:08:48,583] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=load-data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T16:08:38.105006+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T16:08:38.105006+00:00
[2022-08-03 16:08:48,657] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 16:08:48,681] {dbapi.py:231} INFO - Running statement: COPY vehicles FROM '/opt/***/files/vehicle_challenge.csv' WITH DELIMITER ',' CSV HEADER;, parameters: None
[2022-08-03 16:08:48,714] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 50, in insert_data
    post_hook.run("""COPY vehicles FROM '/opt/airflow/files/vehicle_challenge.csv' WITH DELIMITER ',' CSV HEADER;""")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/files/vehicle_challenge.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-08-03 16:08:49,087] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=load-data, execution_date=20220803T160838, start_date=20220803T160848, end_date=20220803T160849
[2022-08-03 16:08:49,155] {standard_task_runner.py:97} ERROR - Failed to execute job 59 for task load-data (could not open file "/opt/***/files/vehicle_challenge.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 537)
[2022-08-03 16:08:49,221] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 16:08:49,367] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
