[2022-08-03 00:32:02,628] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.query-table manual__2022-08-03T00:31:54.873520+00:00 [queued]>
[2022-08-03 00:32:02,652] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.query-table manual__2022-08-03T00:31:54.873520+00:00 [queued]>
[2022-08-03 00:32:02,655] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:32:02,663] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 00:32:02,666] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:32:02,705] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): query-table> on 2022-08-03 00:31:54.873520+00:00
[2022-08-03 00:32:02,725] {standard_task_runner.py:52} INFO - Started process 1802 to run task
[2022-08-03 00:32:02,740] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'query-table', 'manual__2022-08-03T00:31:54.873520+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpkz37xtgd', '--error-file', '/tmp/tmpnf98bcwz']
[2022-08-03 00:32:02,744] {standard_task_runner.py:80} INFO - Job 4: Subtask query-table
[2022-08-03 00:32:02,846] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.query-table manual__2022-08-03T00:31:54.873520+00:00 [running]> on host dc3eb4614e33
[2022-08-03 00:32:03,048] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=query-table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:31:54.873520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T00:31:54.873520+00:00
[2022-08-03 00:32:03,067] {logging_mixin.py:115} INFO - Testing hook
[2022-08-03 00:32:03,108] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 11, in query_table
    post_hook = PostgresOperator(postgres_conn_id = 'postgres')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 373, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2022-08-03 00:32:03,129] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=query-table, execution_date=20220803T003154, start_date=20220803T003202, end_date=20220803T003203
[2022-08-03 00:32:03,185] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task query-table (missing keyword argument 'sql'; 1802)
[2022-08-03 00:32:03,249] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 00:32:03,334] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
